//go:build !generate
// +build !generate

// Code generated by opencorpora-gen; DO NOT EDIT.
package opencorpora

import "strconv"

const (
	PartUnknown PartOfSpeech = iota
	PartAdjf
	PartAdjs
	PartAdvb
	PartComp
	PartConj
	PartGrnd
	PartInfn
	PartIntj
	PartNoun
	PartNpro
	PartNumr
	PartPrcl
	PartPred
	PartPrep
	PartPrtf
	PartPrts
	PartVerb
)

const (
	GrammemeUnknown Grammeme = iota
	Grammeme1per
	Grammeme2per
	Grammeme3per
	GrammemeAbbr
	GrammemeAdjx
	GrammemeAfP
	GrammemeAnph
	GrammemeAnum
	GrammemeApro
	GrammemeArch
	GrammemeCmp2
	GrammemeColl
	GrammemeCoun
	GrammemeDist
	GrammemeDmns
	GrammemeErro
	GrammemeFimp
	GrammemeFixd
	GrammemeGndr
	GrammemeGeox
	GrammemeHypo
	GrammemeInfn
	GrammemeImpe
	GrammemeImpx
	GrammemeInfr
	GrammemeInit
	GrammemeInmx
	GrammemeLitr
	GrammemeMsF
	GrammemeName
	GrammemeOrgn
	GrammemePatr
	GrammemePltm
	GrammemePoss
	GrammemePrdx
	GrammemePrnt
	GrammemeQual
	GrammemeQues
	GrammemeSgtm
	GrammemeSlng
	GrammemeSubx
	GrammemeSupr
	GrammemeSurn
	GrammemeVBe
	GrammemeVBi
	GrammemeVEj
	GrammemeVEn
	GrammemeVEy
	GrammemeVIe
	GrammemeVOy
	GrammemeVSh
	GrammemeVpre
	GrammemeAblt
	GrammemeAccs
	GrammemeActv
	GrammemeAnim
	GrammemeDatv
	GrammemeExcl
	GrammemeFemn
	GrammemeFutr
	GrammemeGen1
	GrammemeGen2
	GrammemeGent
	GrammemeImpf
	GrammemeImpr
	GrammemeInan
	GrammemeIncl
	GrammemeIndc
	GrammemeIntr
	GrammemeLoc1
	GrammemeLoc2
	GrammemeLoct
	GrammemeMasc
	GrammemeMsF2
	GrammemeNeut
	GrammemeNomn
	GrammemePast
	GrammemePerf
	GrammemePlur
	GrammemePres
	GrammemePssv
	GrammemeSing
	GrammemeTran
	GrammemeVoct
)

var partToString = map[PartOfSpeech]string{
	PartUnknown: "unknown",
	PartAdjf:    "ADJF",
	PartAdjs:    "ADJS",
	PartAdvb:    "ADVB",
	PartComp:    "COMP",
	PartConj:    "CONJ",
	PartGrnd:    "GRND",
	PartInfn:    "INFN",
	PartIntj:    "INTJ",
	PartNoun:    "NOUN",
	PartNpro:    "NPRO",
	PartNumr:    "NUMR",
	PartPrcl:    "PRCL",
	PartPred:    "PRED",
	PartPrep:    "PREP",
	PartPrtf:    "PRTF",
	PartPrts:    "PRTS",
	PartVerb:    "VERB",
}

var partFromString = map[string]PartOfSpeech{
	"ADJF": PartAdjf,
	"ADJS": PartAdjs,
	"ADVB": PartAdvb,
	"COMP": PartComp,
	"CONJ": PartConj,
	"GRND": PartGrnd,
	"INFN": PartInfn,
	"INTJ": PartIntj,
	"NOUN": PartNoun,
	"NPRO": PartNpro,
	"NUMR": PartNumr,
	"PRCL": PartPrcl,
	"PRED": PartPred,
	"PREP": PartPrep,
	"PRTF": PartPrtf,
	"PRTS": PartPrts,
	"VERB": PartVerb,
}

var grammemeToString = map[Grammeme]string{
	GrammemeUnknown: "unknown",
	Grammeme1per:    "1per",
	Grammeme2per:    "2per",
	Grammeme3per:    "3per",
	GrammemeAbbr:    "Abbr",
	GrammemeAdjx:    "Adjx",
	GrammemeAfP:     "Af-p",
	GrammemeAnph:    "Anph",
	GrammemeAnum:    "Anum",
	GrammemeApro:    "Apro",
	GrammemeArch:    "Arch",
	GrammemeCmp2:    "Cmp2",
	GrammemeColl:    "Coll",
	GrammemeCoun:    "Coun",
	GrammemeDist:    "Dist",
	GrammemeDmns:    "Dmns",
	GrammemeErro:    "Erro",
	GrammemeFimp:    "Fimp",
	GrammemeFixd:    "Fixd",
	GrammemeGndr:    "GNdr",
	GrammemeGeox:    "Geox",
	GrammemeHypo:    "Hypo",
	GrammemeInfn:    "INFN",
	GrammemeImpe:    "Impe",
	GrammemeImpx:    "Impx",
	GrammemeInfr:    "Infr",
	GrammemeInit:    "Init",
	GrammemeInmx:    "Inmx",
	GrammemeLitr:    "Litr",
	GrammemeMsF:     "Ms-f",
	GrammemeName:    "Name",
	GrammemeOrgn:    "Orgn",
	GrammemePatr:    "Patr",
	GrammemePltm:    "Pltm",
	GrammemePoss:    "Poss",
	GrammemePrdx:    "Prdx",
	GrammemePrnt:    "Prnt",
	GrammemeQual:    "Qual",
	GrammemeQues:    "Ques",
	GrammemeSgtm:    "Sgtm",
	GrammemeSlng:    "Slng",
	GrammemeSubx:    "Subx",
	GrammemeSupr:    "Supr",
	GrammemeSurn:    "Surn",
	GrammemeVBe:     "V-be",
	GrammemeVBi:     "V-bi",
	GrammemeVEj:     "V-ej",
	GrammemeVEn:     "V-en",
	GrammemeVEy:     "V-ey",
	GrammemeVIe:     "V-ie",
	GrammemeVOy:     "V-oy",
	GrammemeVSh:     "V-sh",
	GrammemeVpre:    "Vpre",
	GrammemeAblt:    "ablt",
	GrammemeAccs:    "accs",
	GrammemeActv:    "actv",
	GrammemeAnim:    "anim",
	GrammemeDatv:    "datv",
	GrammemeExcl:    "excl",
	GrammemeFemn:    "femn",
	GrammemeFutr:    "futr",
	GrammemeGen1:    "gen1",
	GrammemeGen2:    "gen2",
	GrammemeGent:    "gent",
	GrammemeImpf:    "impf",
	GrammemeImpr:    "impr",
	GrammemeInan:    "inan",
	GrammemeIncl:    "incl",
	GrammemeIndc:    "indc",
	GrammemeIntr:    "intr",
	GrammemeLoc1:    "loc1",
	GrammemeLoc2:    "loc2",
	GrammemeLoct:    "loct",
	GrammemeMasc:    "masc",
	GrammemeMsF2:    "ms-f",
	GrammemeNeut:    "neut",
	GrammemeNomn:    "nomn",
	GrammemePast:    "past",
	GrammemePerf:    "perf",
	GrammemePlur:    "plur",
	GrammemePres:    "pres",
	GrammemePssv:    "pssv",
	GrammemeSing:    "sing",
	GrammemeTran:    "tran",
	GrammemeVoct:    "voct",
}

var grammemeFromString = map[string]Grammeme{
	"1per": Grammeme1per,
	"2per": Grammeme2per,
	"3per": Grammeme3per,
	"Abbr": GrammemeAbbr,
	"Adjx": GrammemeAdjx,
	"Af-p": GrammemeAfP,
	"Anph": GrammemeAnph,
	"Anum": GrammemeAnum,
	"Apro": GrammemeApro,
	"Arch": GrammemeArch,
	"Cmp2": GrammemeCmp2,
	"Coll": GrammemeColl,
	"Coun": GrammemeCoun,
	"Dist": GrammemeDist,
	"Dmns": GrammemeDmns,
	"Erro": GrammemeErro,
	"Fimp": GrammemeFimp,
	"Fixd": GrammemeFixd,
	"GNdr": GrammemeGndr,
	"Geox": GrammemeGeox,
	"Hypo": GrammemeHypo,
	"INFN": GrammemeInfn,
	"Impe": GrammemeImpe,
	"Impx": GrammemeImpx,
	"Infr": GrammemeInfr,
	"Init": GrammemeInit,
	"Inmx": GrammemeInmx,
	"Litr": GrammemeLitr,
	"Ms-f": GrammemeMsF,
	"Name": GrammemeName,
	"Orgn": GrammemeOrgn,
	"Patr": GrammemePatr,
	"Pltm": GrammemePltm,
	"Poss": GrammemePoss,
	"Prdx": GrammemePrdx,
	"Prnt": GrammemePrnt,
	"Qual": GrammemeQual,
	"Ques": GrammemeQues,
	"Sgtm": GrammemeSgtm,
	"Slng": GrammemeSlng,
	"Subx": GrammemeSubx,
	"Supr": GrammemeSupr,
	"Surn": GrammemeSurn,
	"V-be": GrammemeVBe,
	"V-bi": GrammemeVBi,
	"V-ej": GrammemeVEj,
	"V-en": GrammemeVEn,
	"V-ey": GrammemeVEy,
	"V-ie": GrammemeVIe,
	"V-oy": GrammemeVOy,
	"V-sh": GrammemeVSh,
	"Vpre": GrammemeVpre,
	"ablt": GrammemeAblt,
	"accs": GrammemeAccs,
	"actv": GrammemeActv,
	"anim": GrammemeAnim,
	"datv": GrammemeDatv,
	"excl": GrammemeExcl,
	"femn": GrammemeFemn,
	"futr": GrammemeFutr,
	"gen1": GrammemeGen1,
	"gen2": GrammemeGen2,
	"gent": GrammemeGent,
	"impf": GrammemeImpf,
	"impr": GrammemeImpr,
	"inan": GrammemeInan,
	"incl": GrammemeIncl,
	"indc": GrammemeIndc,
	"intr": GrammemeIntr,
	"loc1": GrammemeLoc1,
	"loc2": GrammemeLoc2,
	"loct": GrammemeLoct,
	"masc": GrammemeMasc,
	"ms-f": GrammemeMsF2,
	"neut": GrammemeNeut,
	"nomn": GrammemeNomn,
	"past": GrammemePast,
	"perf": GrammemePerf,
	"plur": GrammemePlur,
	"pres": GrammemePres,
	"pssv": GrammemePssv,
	"sing": GrammemeSing,
	"tran": GrammemeTran,
	"voct": GrammemeVoct,
}

var allPartsOfSpeech = []PartOfSpeech{
	PartAdjf,
	PartAdjs,
	PartAdvb,
	PartComp,
	PartConj,
	PartGrnd,
	PartInfn,
	PartIntj,
	PartNoun,
	PartNpro,
	PartNumr,
	PartPrcl,
	PartPred,
	PartPrep,
	PartPrtf,
	PartPrts,
	PartVerb,
}

var allGrammemes = []Grammeme{
	Grammeme1per,
	Grammeme2per,
	Grammeme3per,
	GrammemeAbbr,
	GrammemeAdjx,
	GrammemeAfP,
	GrammemeAnph,
	GrammemeAnum,
	GrammemeApro,
	GrammemeArch,
	GrammemeCmp2,
	GrammemeColl,
	GrammemeCoun,
	GrammemeDist,
	GrammemeDmns,
	GrammemeErro,
	GrammemeFimp,
	GrammemeFixd,
	GrammemeGndr,
	GrammemeGeox,
	GrammemeHypo,
	GrammemeInfn,
	GrammemeImpe,
	GrammemeImpx,
	GrammemeInfr,
	GrammemeInit,
	GrammemeInmx,
	GrammemeLitr,
	GrammemeMsF,
	GrammemeName,
	GrammemeOrgn,
	GrammemePatr,
	GrammemePltm,
	GrammemePoss,
	GrammemePrdx,
	GrammemePrnt,
	GrammemeQual,
	GrammemeQues,
	GrammemeSgtm,
	GrammemeSlng,
	GrammemeSubx,
	GrammemeSupr,
	GrammemeSurn,
	GrammemeVBe,
	GrammemeVBi,
	GrammemeVEj,
	GrammemeVEn,
	GrammemeVEy,
	GrammemeVIe,
	GrammemeVOy,
	GrammemeVSh,
	GrammemeVpre,
	GrammemeAblt,
	GrammemeAccs,
	GrammemeActv,
	GrammemeAnim,
	GrammemeDatv,
	GrammemeExcl,
	GrammemeFemn,
	GrammemeFutr,
	GrammemeGen1,
	GrammemeGen2,
	GrammemeGent,
	GrammemeImpf,
	GrammemeImpr,
	GrammemeInan,
	GrammemeIncl,
	GrammemeIndc,
	GrammemeIntr,
	GrammemeLoc1,
	GrammemeLoc2,
	GrammemeLoct,
	GrammemeMasc,
	GrammemeMsF2,
	GrammemeNeut,
	GrammemeNomn,
	GrammemePast,
	GrammemePerf,
	GrammemePlur,
	GrammemePres,
	GrammemePssv,
	GrammemeSing,
	GrammemeTran,
	GrammemeVoct,
}

func (p PartOfSpeech) String() string {
	if s, ok := partToString[p]; ok {
		return s
	}
	return "PartOfSpeech(" + strconv.Itoa(int(p)) + ")"
}

func ParsePartOfSpeech(s string) (PartOfSpeech, bool) {
	p, ok := partFromString[s]
	return p, ok
}

func AllPartsOfSpeech() []PartOfSpeech {
	out := make([]PartOfSpeech, len(allPartsOfSpeech))
	copy(out, allPartsOfSpeech)
	return out
}
func (g Grammeme) String() string {
	if s, ok := grammemeToString[g]; ok {
		return s
	}
	return "Grammeme(" + strconv.Itoa(int(g)) + ")"
}

func ParseGrammeme(s string) (Grammeme, bool) {
	g, ok := grammemeFromString[s]
	return g, ok
}

func AllGrammemes() []Grammeme {
	out := make([]Grammeme, len(allGrammemes))
	copy(out, allGrammemes)
	return out
}
