package opencorpora

import "context"

// PartOfSpeech represents a part of speech value from OpenCorpora.
// Concrete values are generated by cmd/opencorpora-gen from the upstream dictionary.
type PartOfSpeech uint16

// Grammeme represents a single grammeme marker (gender, number, etc.).
// Concrete values are generated by cmd/opencorpora-gen from the upstream dictionary.
type Grammeme uint16

// WordEntry describes a single word form from a lexeme.
type WordEntry struct {
    LexemeID  int
    Form      string
    Lemma     string
    POS       PartOfSpeech
    Grammemes []Grammeme
}

// Option configures dictionary loading.
type Option func(*Options)

// Options hold configuration for downloading and parsing the dictionary file.
type Options struct {
    DictionaryURL string
    CacheDir      string
    ZipPath       string
    TextPath      string
}

// Apply sets defaults for empty fields.
func (o *Options) Apply(ctx context.Context) error {
    if o.DictionaryURL == "" {
        o.DictionaryURL = DefaultDictionaryURL
    }
    if o.CacheDir == "" {
        cache, err := defaultCacheDir()
        if err != nil {
            return err
        }
        o.CacheDir = cache
    }
    if o.ZipPath == "" {
        o.ZipPath = defaultZipPath(o.CacheDir)
    }
    if o.TextPath == "" {
        o.TextPath = defaultTextPath(o.CacheDir)
    }
    return ctx.Err()
}
